CREATE TABLE PERSON (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(400) NOT NULL,
    surname VARCHAR(400) NULL,
    age INTEGER NULL,
    city VARCHAR(400) NULL,
    country VARCHAR(400) NULL
);