CREATE TABLE CUSTOMERS (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    first_name VARCHAR(400) NOT NULL,
    last_name VARCHAR(400) NOT NULL,
    email VARCHAR(400) NOT NULL,
    username VARCHAR(400) NOT NULL
);

CREATE TABLE ORDERS (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    customers_id BIGINT NOT NULL,
    status VARCHAR(400) NOT NULL,
    payment_type VARCHAR(400) NOT NULL,
    total_price VARCHAR(400) NOT NULL,
    FOREIGN KEY (customers_id) REFERENCES CUSTOMERS(id)
);

CREATE TABLE PRODUCTS (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    price VARCHAR(255) NOT NULL,
    orders_id BIGINT NOT NULL,
    FOREIGN KEY (orders_id) REFERENCES ORDERS(id)
);